Makefile: Use = for CFLAGS, instead of ?=
dlbeer/quirc pull request #95
Opened 2021-03-22 01:33 UTC by yamt

* There seeems no good reasons to use ?= here.

* Some make (eg. BSD make I installed with "brew install bsdmake")
  have the default CFLAGS set. Using ?= here means to use the default.
  I guess it isn't the intention of this Makefile.

2021-03-24 09:11 UTC, kaworu requested changes
`?=` is intended here and a feature, allowing to set `QUIRC_MAX_REGIONS` for example (see the [README](https://github.com/dlbeer/quirc#installation)).

From the CFLAGS we set, I'm personally Ok with make and/or the system overriding `-Wall` and `-03`. On the other hand,`-fPIC` is not optional. So I could see something like this:

```make
CFLAGS ?= -O3 -Wall
CFLAGS += -fPIC
```

2021-03-24 09:39 UTC, yamt commented
> `?=` is intended here and a feature, allowing to set `QUIRC_MAX_REGIONS` for example (see the [README](https://github.com/dlbeer/quirc#installation)).
> 
> From the CFLAGS we set, I'm personally Ok with make and/or the system overriding `-Wall` and `-03`. On the other hand,`-fPIC` is not optional. So I could see something like this:
> 
> ```makefile
> CFLAGS ?= -O3 -Wall
> CFLAGS += -fPIC
> ```

you can override variables defined with `=`.

2021-03-25 05:05 UTC, yamt commented
@kaworu i guess i now understand what you meant. i updated the patch accordingly.

2021-03-28 18:41 UTC, kaworu commented
Out of curiosity, what are the default `CFLAGS` defined by bmake installed by brew on your system?

2021-03-28 23:04 UTC, yamt commented
`-Os -pipe`.
it's from the default sys.mk. it can be disabled with `bsdmake -r`.

2021-04-03 18:38 UTC, kaworu commented
Typically I believe `-Os -pipe` is reasonable to replace our default `-O3 -Wall`. Again, the only issue I see is about the `-fPIC` which the patch doesn't address as-is.

2021-04-07 23:30 UTC, yamt commented
> Typically, I believe `-Os -pipe` is reasonable to replace our default `-O3 -Wall`.
> I don't know a build system that doesn't honor the environment CFLAGS or CC.
> The env might have some strong opinion on CFLAGS like `-fstack-protector-strong` or cross compiling overriding CC as well etc.

when you say the environment, you specifically mean the environment variables, and you are not happy with "make CFLAGS=${CFLAGS}", right?

> Again, the only issue I see is about the `-fPIC` which the patch doesn't address as-is.

i want to make it use `-Wall` by default too. also, i want to keep it overridable by user.

2021-04-07 23:40 UTC, yamt commented
also, IMO, -fPIC should be overridable as well because it's very compiler/platform dependent.

2021-04-08 00:30 UTC, yamt commented
after thinking a bit, i tend to think documentation is enough. https://github.com/dlbeer/quirc/pull/101

2021-04-08 00:30 UTC, closed without merging